#!/usr/bin/env python3
"""
Generate Markdown docs for a composite GitHub Action.

This script intentionally avoids third-party YAML dependencies and only
parses the limited structure used by action.yml files in this repository.
"""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple


AUTOGEN_START = "<!-- AUTOGENERATED:ACTION-DOC -->"
AUTOGEN_END = "<!-- END AUTOGENERATED:ACTION-DOC -->"


@dataclass
class ActionInput:
    name: str
    description: str = ""
    required: bool = False
    default: Optional[str] = None


@dataclass
class ActionMetadata:
    name: str
    description: str
    inputs: List[ActionInput] = field(default_factory=list)


def parse_value(raw: str) -> Optional[str] | bool:
    raw = raw.strip()
    if not raw:
        return ""

    lowered = raw.lower()
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    if lowered == "null":
        return None

    if raw.startswith("'") and raw.endswith("'"):
        inner = raw[1:-1]
        return inner.replace("''", "'")

    if raw.startswith('"') and raw.endswith('"'):
        return ast.literal_eval(raw)

    return raw


def parse_action_yaml(path: Path) -> ActionMetadata:
    name: Optional[str] = None
    description: Optional[str] = None
    inputs: List[ActionInput] = []

    current_input: Optional[ActionInput] = None
    in_inputs = False

    for raw_line in path.read_text().splitlines():
        if not raw_line.strip() or raw_line.strip().startswith("#"):
            continue

        indent = len(raw_line) - len(raw_line.lstrip(" "))
        line = raw_line.strip()

        if indent == 0:
            current_input = None
            if line == "inputs:":
                in_inputs = True
                continue
            in_inputs = False

            if ":" in line:
                key, value = _split_key_value(line)
                parsed_value = parse_value(value)
                if key == "name":
                    name = str(parsed_value)
                elif key == "description":
                    description = str(parsed_value)
            continue

        if in_inputs:
            if indent == 2 and line.endswith(":"):
                input_name = line[:-1]
                current_input = ActionInput(name=input_name)
                inputs.append(current_input)
                continue

            if indent >= 4 and current_input and ":" in line:
                key, value = _split_key_value(line)
                parsed_value = parse_value(value)
                if key == "description":
                    current_input.description = str(parsed_value or "")
                elif key == "required":
                    current_input.required = bool(parsed_value)
                elif key == "default":
                    current_input.default = None if parsed_value is None else str(parsed_value)

    if name is None or description is None:
        raise ValueError(f"Missing name or description in {path}")

    return ActionMetadata(name=name, description=description, inputs=inputs)


def _split_key_value(line: str) -> Tuple[str, str]:
    key, value = line.split(":", 1)
    return key.strip(), value.strip()


def render_table_value(value: Optional[str]) -> str:
    if value is None or value == "":
        return "—"
    return value


def build_autogen_section(metadata: ActionMetadata, action_path: Path) -> str:
    lines: List[str] = []
    lines.append(AUTOGEN_START)
    try:
        rel_path = action_path.relative_to(Path.cwd()).as_posix()
    except ValueError:
        rel_path = action_path.as_posix()
    lines.append(f"<!-- Source: {rel_path} -->")
    lines.append(f"# {metadata.name}")
    lines.append("")
    lines.append(metadata.description)
    lines.append("")
    lines.append("## Inputs")
    lines.append("")
    lines.append("| Input | Required | Default | Description |")
    lines.append("| --- | --- | --- | --- |")
    for action_input in metadata.inputs:
        required = "✅" if action_input.required else "❌"
        default = render_table_value(action_input.default)
        description = action_input.description or "—"
        lines.append(f"| `{action_input.name}` | {required} | {default} | {description} |")
    lines.append("")
    lines.append(AUTOGEN_END)
    lines.append("")
    return "\n".join(lines)


def merge_with_existing(output_path: Path, generated_section: str) -> str:
    if not output_path.exists():
        return generated_section + "## Usage\n\n<!-- Add usage examples below -->\n"

    existing = output_path.read_text()
    if AUTOGEN_START not in existing or AUTOGEN_END not in existing:
        raise RuntimeError(
            f"{output_path} exists but is missing autogen markers ({AUTOGEN_START} / {AUTOGEN_END})."
        )

    before, _, rest = existing.partition(AUTOGEN_START)
    _, _, after = rest.partition(AUTOGEN_END)
    return before + generated_section + after


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate documentation for a composite GitHub Action.")
    parser.add_argument("--action", required=True, help="Path to action.yml")
    parser.add_argument("--output", required=True, help="Path to output Markdown file")
    args = parser.parse_args()

    action_path = Path(args.action).resolve()
    output_path = Path(args.output)

    metadata = parse_action_yaml(action_path)
    generated_section = build_autogen_section(metadata, action_path)
    final_content = merge_with_existing(output_path, generated_section)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(final_content)


if __name__ == "__main__":
    main()
