name: "Run Red-DiscordBot"
description: "Sets up Red-DiscordBot configuration and runs the bot."

# This is just a test. It makes no sense to run Red-DiscordBot in CI. It is useful for local testing with nektos/act.
# We will create a new action to run actual Red-DiscordBot tests.

inputs:
  token:
    description: "Discord bot token"
    required: true
  optional_args:
    description: "Optional extra arguments for redbot"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Red-DiscordBot configuration
      shell: bash
      run: |
        echo "ðŸ“ Creating ~/.config/Red-DiscordBot directory"
        mkdir -p ~/.config/Red-DiscordBot

        echo "ðŸ“ Writing config.json"
        CONFIG_JSON='{"tinkerer":{"DATA_PATH":"/app","COG_PATH_APPEND":"cogs","CORE_PATH_APPEND":"core","STORAGE_TYPE":"JSON","STORAGE_DETAILS":{}}}'
        echo "$CONFIG_JSON" > ~/.config/Red-DiscordBot/config.json

    - name: Run Red-DiscordBot
      shell: bash
      run: |
        echo "ðŸš€ Starting Red-DiscordBot"
        python3 -m redbot tinkerer --token "${{ inputs.token }}" ${{ inputs.optional_args }}
