name: "Install Red-DiscordBot"
description: "Downloads a Red-DiscordBot build artifact and installs it using uv."

inputs:
  artifact_name:
    description: "Optional artifact name to download. Default: red-discordbot-build"
    required: false

runs:
  using: "composite"
  steps:
    # Step 1 — Download the artifact
    - name: Download Red-DiscordBot artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name || 'red-discordbot-build' }}
        path: ./dist

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 2 — Install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v1

    # Step 4 — Install the downloaded package
    - name: Install Red-DiscordBot
      shell: bash
      run: |
        uv install ./dist/*

    # Step 5 — Verify installation
    - name: Verify installation
      shell: bash
      run: |
        uvx python -c "import red; print('✅ Red-DiscordBot installed successfully')"
