name: "Install Red-DiscordBot"
description: "Downloads a Red-DiscordBot build artifact and installs it using uv."

inputs:
  artifact_name:
    description: "Optional artifact name to download. Default: red-discordbot-build"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download Red-DiscordBot artifact
      if: env.ACT != 'true'  # Skip download when running with act
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name || 'red-discordbot-build' }}
        path: ./dist

    - name: Copy local artifact for act
      if: env.ACT == 'true'
      run: |
        # Use the mounted path inside container path\to\Red-DiscordBot\dist:/tmp/dist
        mkdir -p ./dist
        if compgen -G "/tmp/dist/*" > /dev/null; then
          cp /tmp/dist/* ./dist/
        else
          echo "❌ No files found in /tmp/dist. Did you mount the host folder correctly?"
          exit 1
        fi

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Install Red-DiscordBot
      shell: bash
      run: |
        uv pip install ./dist/*

    - name: Verify installation
      shell: bash
      run: |
        uvx python -c "import red; print('✅ Red-DiscordBot installed successfully')"
